### ISSUE TITLE
Problem with different Namespaces and Wrapped Element

### ISSUE THREAD

**Issue by mrfoxy** [dmak/jaxb-xew-plugin#21]
Hello, If an element in a namspace imports a complextype from an other namespace, which only include one element unbounded ( a List), the namespace in the generated Class for the wrapped item element is missing / wrong. See also Issue #8  .
Example:

[test.xsd / testnamespace]
`<xs:element name="notes" type="com:WsNotes" minOccurs="0" />`

[com:xsd / common namespace]
`<xs:complexType name="WsNotes">
        <xs:sequence>
            <xs:element name="note" type="com:WsNote" minOccurs="0" maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
    </xs:complexType>`

Generated Class:

`@XmlElementWrapper(name = "notes")
@XmlElement(name = "note")      // Namesspace common (com) is missing!
protected List<WsNote> notes;`

ciao René

**Comment by valsoray17** [comment]
Seems like this time it generates namespaces for all elements even if the elementFormDefault is set to unqualified. This results in missed elements after unmarshaling as the elements are not qualified with the prefix.

Is it possible to tell xew not to generate the namespaces for wrapper elements?

**Comment by dmak** [comment]
Could you please share the complete schema and sample XML file that demonstrates the problem?

**Comment by valsoray17** [comment]
Thanks for getting back so quickly. Here is the sample
[TestSchema]
```xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="testNamespace"
		   targetNamespace="testNamespace" elementFormDefault="unqualified"
		   attributeFormDefault="unqualified">

	<xs:element name="element1" type="ElementType1">
		<xs:annotation>
			<xs:documentation>Root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="ElementType1">
		<xs:sequence>
			<xs:element name="stringList" type="stringListType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="stringListType">
		<xs:sequence>
			<xs:element name="listItem" type="xs:string" minOccurs="0"
						maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>
```
[TestXml.xml]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<n:element1 xmlns:n="testNamespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<stringList>
		<listItem>str1</listItem>
		<listItem>str2</listItem>
		<listItem>str3</listItem>
		<listItem>str4</listItem>
	</stringList>
</n:element1>
```

So the generated code has namespace = "testNamespace"
```java
@XmlElement(name = "listItem", namespace = "testNamespace")
protected List<String> stringList;
```
In this case the list is empty. If the namespace is removed from the annotation then the list contains data.
I know that schema is not correct, but still valid and I don't have possibility to fix it.

Thanks.

**Comment by dmak** [comment]
@valsoray17: Thanks for posting the example. I confirm that there is a problem. I suggest to leave this very (already closed) issue since it was reopened many times and became too complicated. I have spawned the new issue #40 – let's continue the discussion there.
