### ISSUE TITLE
Gradle, Ant, and CLI build fail with "Provider com.sun.tools.xjc.addon.xew.XmlElementWrapperPlugin not a subtype"

### ISSUE THREAD

**Issue by davidmichaelkarr** [dmak/jaxb-xew-plugin#37]
Just so it's clear, I don't think this is a real issue with your code. I can demonstrate the error using your extension, but I can demonstrate the same error without your code. Perhaps you're familiar with this issue and might have some advice on how to fix this.

I've initially configured a Gradle build referencing this extension using the Ant XJC task. I also did the same with an Ant build script, along with a simple Bash script calling the XJCFacade class directly.

All of these fail with this:

	Exception in thread "main" java.util.ServiceConfigurationError: com.sun.tools.xjc.Plugin: Provider com.sun.tools.xjc.addon.xew.XmlElementWrapperPlugin not a subtype
		at java.util.ServiceLoader.fail(ServiceLoader.java:231)
		at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
		at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:369)
		at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
		at com.sun.tools.xjc.Options.findServices(Options.java:957)
		at com.sun.tools.xjc.Options.getAllPlugins(Options.java:374)
		at com.sun.tools.xjc.Options.parseArgument(Options.java:688)
		at com.sun.tools.xjc.Driver$OptionsEx.parseArgument(Driver.java:511)
		at com.sun.tools.xjc.Options.parseArguments(Options.java:809)
		at com.sun.tools.xjc.Driver.run(Driver.java:240)
		at com.sun.tools.xjc.Driver.run(Driver.java:200)
		at com.sun.tools.xjc.Driver._main(Driver.java:123)
		at com.sun.tools.xjc.Driver.access$000(Driver.java:80)
		at com.sun.tools.xjc.Driver$1.run(Driver.java:103)

Although I get this error using this plugin, I don't think this is a particular issue with your plugin, because I see the same symptom with every other JAXB extension I've tried to use.

However, if I run the build using the  "cxf-xjc-plugin" in Maven, I do not have this problem. I'm trying to convert this build from Maven to Gradle, so I need to fix this problem.

I'm running my builds with JDK 7, and I'm currently using version 2.2.6 of the JAXB api, impl, and xjc jars.

**Comment by dmak** [comment]
Quick look at your description brings me to only one idea: you have several `jaxb-xjc` libraries in your classpath. Try to exclude those (in maven that can be achieved by using `<dependency><excludes>`, but as far Gradle is concerned I cannot tell you for sure) and leave only one library version. The reason why it worked in Maven could be that by co-incidence `cxf-xjc-plugin` depends on the same version of `jaxb-xjc` as `jaxb-xew-plugin`.

**Comment by davidmichaelkarr** [comment]
So you don't "see" multiple jaxb-xjc jars in my classpath, you're just suggesting that that might be the problem?

I have some debugging code that is printing out the jaxb gradle configuration, showing all the jars being provided as its classpath, and there's only one jaxb-xjc jar.  In any case, I get the same error when I manually construct the XJCFacade command line, where I specify the exact jars that go into the classpath, which includes only one "jaxb-xjc" jar.

**Comment by dmak** [comment]
In this case maybe you can share the whole Gradle project (e.g. with some minimalistic XSD) that reproduces the problem (e.g. put it as ZIP to some server and give me the URL to download)?

**Comment by davidmichaelkarr** [comment]
Actually, I can reproduce the problem here with just my shell script calling XJCFacade and the dependent jars. It gets this error before it even attempts to look at the xjc command-line arguments (like the schema). I'll try to package that up.

**Comment by davidmichaelkarr** [comment]
Technically, I could insert all the required information as text here. If I insert the text of the shell script and the GAV references, you should be able to construct the same thing.
The GAV references are:
	jaxb 'com.sun.xml.bind:jaxb-xjc:2.2.7'
	jaxb "com.github.jaxb-xew-plugin:jaxb-xew-plugin:1.4"
	jaxb "net.java.dev.jaxb2-commons:jaxb-fluent-api:2.1.8"

The shell script is this:
	#! /bin/bash
	java -classpath "lib/commons-beanutils-1.7.0.jar;lib/commons-lang-2.2.jar;lib/commons-logging-1.1.1.jar;lib/istack-commons-runtime-2.16.jar;lib/jaxb2-basics-runtime-0.6.5.jar;lib/jaxb2-basics-tools-0.6.5.jar;lib/jaxb-api-2.2.7.jar;lib/jaxb-core-2.2.7.jar;lib/jaxb-fluent-api-2.1.8.jar;lib/jaxb-xew-plugin-1.4.jar;lib/jaxb-xjc-2.2.7.jar" com.sun.tools.xjc.XJCFacade -extension

**Comment by davidmichaelkarr** [comment]
I've refined this script a bit (removed some jars that don't affect the failure of the test), down to this:

 #! /bin/bash
 cp="\
 lib/jaxb-core-2.2.7.jar:\
 lib/jaxb-xjc-2.2.7.jar:\
 lib/jaxb-fluent-api-2.1.8.jar:\
 lib/jaxb-xew-plugin-1.4.jar:\
 "
 java -classpath "$cp" com.sun.tools.xjc.XJCFacade -extension

**Comment by davidmichaelkarr** [comment]
I also ran this test case in the debugger and set a breakpoint in "java.util.ServiceLoader$LazyIterator.next" to see what the exception is really for. The information that is left out of the exception message (but is probably assumed) is "not a subtype of com.sun.tools.xjc.Plugin". I examined your plugin class along with the other one, and verified that they are subclasses of com.sun.tools.xjc.Plugin. They only reasonable way this comparison could fail is if the two classes were loaded by different classloaders. I don't know what to do with that information.

**Comment by dmak** [comment]
I have posted the answer to [stackoverflow](http://stackoverflow.com/a/28197814/267197). If you come up with working ANT configuration (it should be very straightforward), please post it here and I will update the documentation.

**Comment by davidmichaelkarr** [comment]
Outstanding. I'll proceed with building that.

**Comment by davidmichaelkarr** [comment]
Ok.  I'm still trying to figure out how to translate my Gradle dependencies for xjc into the "classpath" form required by the XJCTask, but I've fixed my Ant "build.xml", clearly separating the classpath required to "reference" XJC from the classpath required to "run" XJC.

The result looks like this:

	<?xml version="1.0" encoding="UTF-8"?>
	<project name="SunlightDataService" default="build" basedir=".">
	  <property name="baseGradleCache" value="C:/Users/dk068x/.gradle/caches/modules-2/files-2.1"/>
	  <path id="compile.classpath">
	    <fileset dir="${baseGradleCache}/com.sun.xml.bind\jaxb-xjc\2.2.7\f351eed8b1ee9a1dd242bf81bf7a391c40a16d18">
	      <include name="jaxb-xjc-2.2.7.jar"/>
	    </fileset>
	    <fileset dir="${baseGradleCache}/javax.xml.bind/jaxb-api/2.2.7/2f51c4bb4724ea408096ee9100ff2827e07e5b7c">
	      <include name="jaxb-api-2.2.7.jar"/>
	    </fileset>
	    <fileset dir="${baseGradleCache}/com.sun.xml.bind/jaxb-core/2.2.7/f327817188a7dce503ae3c667c5931077630b0a1">
	      <include name="jaxb-core-2.2.7.jar"/>
	    </fileset>
	    <fileset dir="${baseGradleCache}/commons-logging\commons-logging\1.1.1\5043bfebc3db072ed80fbd362e7caf00e885d8ae">
	      <include name="commons-logging-1.1.1.jar"/>
	    </fileset>
	    <fileset dir="${baseGradleCache}/commons-lang\commons-lang\2.2\ef6449b62937bbd10e29ba9ed9a852754b861d26">
	      <include name="commons-lang-2.2.jar"/>
	    </fileset>
	  </path>
	  <path id="xjc.classpath">
	    <fileset dir="${baseGradleCache}/com.github.jaxb-xew-plugin/jaxb-xew-plugin/1.4/3f111feb9f7fecc289b4835cd4e23009934ac85f">
	      <include name="jaxb-xew-plugin-1.4.jar"/>
	    </fileset>
	    <fileset dir="${baseGradleCache}/net.java.dev.jaxb2-commons/jaxb-fluent-api/2.1.8/9a0c55565f17599930d1265546dbd88b2a14cbf0">
	      <include name="jaxb-fluent-api-2.1.8.jar"/>
	    </fileset>
	    <fileset dir="${baseGradleCache}/org.jvnet.jaxb2_commons/jaxb2-basics-tools/0.6.5/6f582f7a158f19b64f3b5fb1ec1495cedbd7fda">
	      <include name="jaxb2-basics-tools-0.6.5.jar"/>
	    </fileset>
	  </path>
	  <taskdef name="xjc" classname="com.sun.tools.xjc.XJCTask">
	    <classpath>
	      <path refid="compile.classpath"/>
	    </classpath>
	  </taskdef>

	  <target name="build">
	    <mkdir dir="gen"/>
	    <xjc destdir="gen" schema="schema/serviceCallResults.xsd"
		 package="com.att.sunlight.service.domain.serviceCallResults"
		 extension="true" removeOldOutput="true">
	      <classpath refid="xjc.classpath"/>
	      <arg value="-Xxew"/>
	      <arg value="-Xfluent-api"/>
	    </xjc>
	  </target>
	</project>

I'll add a similar sample for Gradle if you like (once I figure out that translation problem).

**Comment by davidmichaelkarr** [comment]
Ok.  I now have this working in my test Gradle build. I still have to integrate this into my real build script, but this was likely the main issue.  The sample looks like this:

	apply plugin: 'java'
	apply plugin: 'maven'
	apply plugin: 'war'

	sourceCompatibility = 1.7
	targetCompatibility = 1.7

	repositories {
	  maven { url "http://repo1.maven.org/maven2/" }
	}

	configurations {
	  xjc
	}

	dependencies {
	  compile 'com.sun.xml.bind:jaxb-xjc:2.2.7'
	  compile 'com.sun.xml.bind:jaxb-core:2.2.7'
	  compile 'javax.xml.bind:jaxb-api:2.2.7'

	  xjc "com.github.jaxb-xew-plugin:jaxb-xew-plugin:1.4"
	  xjc "net.java.dev.jaxb2-commons:jaxb-fluent-api:2.1.8"
	}

	task processXSDs() << {
	  ant.taskdef(name: 'xjc', classname: 'com.sun.tools.xjc.XJCTask',
		      classpath: configurations.compile.asPath)

	  ant.xjc(destdir: 'tmp',
		  package: "com.att.sunlight.service.domain.serviceCallResults",
		  extension: true) {
	    classpath() {
	      configurations.xjc.each {
		File file -> pathelement(location: file)
	      }
	    }
	    schema(dir: "schema", includes: "serviceCallResults.xsd")
	    arg(value: "-Xxew")
	    arg(value: "-Xfluent-api")
	  }
	}

	compileJava.dependsOn processXSDs
