### ISSUE TITLE
Calling xew from command line fails with "unrecognized parameter -Xxew"

### ISSUE THREAD

**Issue by davidmichaelkarr** [dmak/jaxb-xew-plugin#38]
As an attempt to get more information for my other issue ("Provider xx not a subtype"), I'm trying to run xjc directly from the command line, specifying the same options I'm trying to use in the build.

I'm using the xjc from the JDK, (7 or 8) and attempting the following command line:

    xjc -extension  -classpath "lib/jaxb-fluent-api-2.1.8.jar;lib/jaxb-xew-plugin-1.4.jar" -Xxew -summary target/xew-summary.txt -instantiate lazy -Xfluent-api schema/serviceCallResults.xsd

This fails with "unrecognized parameter -Xxew" and then gives me the "usage" page.

What am I missing?

**Comment by highsource** [comment]
NB: http://stackoverflow.com/questions/28145306/how-to-use-jaxb-extensions-on-xjc-command-line/28146236#28146236

**Comment by highsource** [comment]
From my PoV, not an issue in XEW but rather in XJC. Will most probably not addressed there as well (they won't drop renaming).

**Comment by davidmichaelkarr** [comment]
I suppose this isn't that disappointing.  I would have only considered this as a last resort. I'll close this issue myself. However, I've still made no progress in my efforts to use this extension (along with "Fluent API") in anything but the CXF Maven plugin, ideally using either the Ant XJC task or the XJCFacade class.

**Comment by dmak** [comment]
I was able to execute Xew as follows:

`java -cp jaxb-api-2.2.7.jar;jaxb-core-2.2.7.jar;jaxb-xjc-2.2.7.jar;commons-logging-1.1.1.jar;jaxb-xew-plugin-1.2.jar com.sun.tools.xjc.XJCFacade -verbose -extension -no-header -Xxew -d src xsd`

However for version 1.3 and higher of the plugin I get issue #37, so I think this is somehow related to `jaxb2-basics-tools`.

**Comment by highsource** [comment]
Which version of jaxb2-basics do you have on 1.3?
Does it work with 2.2.1?
The only thing I can imagine is this issue:
https://github.com/highsource/maven-jaxb2-plugin/issues/24

**Comment by davidmichaelkarr** [comment]
Perhaps these comments are more relevant to #37, not this issue.
