### ISSUE TITLE
Issue with namespaces in case of unqualified schema

### ISSUE THREAD

**Issue by dmak** [dmak/jaxb-xew-plugin#40]
Originally reported in [issue#21](https://github.com/dmak/jaxb-xew-plugin/issues/21#issuecomment-75269568) by @valsoray17:

[TestSchema]
```xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="testNamespace"
		   targetNamespace="testNamespace" elementFormDefault="unqualified"
		   attributeFormDefault="unqualified">

	<xs:element name="element1" type="ElementType1">
		<xs:annotation>
			<xs:documentation>Root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="ElementType1">
		<xs:sequence>
			<xs:element name="stringList" type="stringListType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="stringListType">
		<xs:sequence>
			<xs:element name="listItem" type="xs:string" minOccurs="0"
						maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>
```
[TestXml.xml]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<n:element1 xmlns:n="testNamespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<stringList>
		<listItem>str1</listItem>
		<listItem>str2</listItem>
		<listItem>str3</listItem>
		<listItem>str4</listItem>
	</stringList>
</n:element1>
```

The generated code defines namespace = "testNamespace":
```java
@XmlElement(name = "listItem", namespace = "testNamespace")
protected List<String> stringList;
```
In this case the list is empty after unmarshaling. If the namespace is removed from the annotation then the list contains data.
I know that schema is not correct, but still valid and I don't have possibility to fix it.

**Comment by dmak** [comment]
The reason why Xew plugin pulls the schema from `@XmlSchema` annotation from `package-info.java` is to solve the issue #21 when collection belongs to one namespace and collection container – to another. In case if collection namespace is defaulted with `@XmlSchema` package annotation as most used (that that is actually the most frequent case), it should be correctly set. So fix for issue #21 and this issue are mutually exclusive.

* One workaround is to use v1.3 of the plugin for unqualified schema, and v1.4 for qualified schema.
* Another solution would be to revert fix for issue #21 and advise to use `-npa` option for XJC.
* Submit a bug for JAXB, because `@XmlSchema` annotation is missing `elementFormDefault` and `attributeFormDefault` which are obviously defined for schema. Namely it should be `@javax.xml.bind.annotation.XmlSchema(namespace = "testNamespace", elementFormDefault=javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED)`, then Xew plugin can benefit from this information.
* Any other way to find out whether the schema definition was unqualified?

**Comment by dmak** [comment]
I was wrong in respect to JAXB: it sets `elementFormDefault` only for qualified schema, hence it is possible to overcome the problem. Volunteers are welcomed to test [jaxb-xew-plugin-1.5-SNAPSHOT.jar](https://oss.sonatype.org/content/repositories/snapshots/com/github/jaxb-xew-plugin/jaxb-xew-plugin/1.5-SNAPSHOT/jaxb-xew-plugin-1.5-20150305.183959-1.jar).

**Comment by valsoray17** [comment]
I'll give it a try later today.

Thanks!

**Comment by valsoray17** [comment]
Hm, now I have this error in maven:

Execution service-provider of goal org.codehaus.mojo:jaxb2-maven-plugin:1.6:xjc failed: A required class was missing while executing org.codehaus.mojo:jaxb2-maven-plugin:1.6:xjc: org/jvnet/jaxb2_commons/plugin/AbstractParameterizablePlugin

I installed the file you provided in my local repository and updated the project's POM file to reference 1.5-SNAPSHOT.

**Comment by dmak** [comment]
Please, follow the example for `jaxb2-maven-plugin` on [start page](https://github.com/dmak/jaxb-xew-plugin#jaxb2-maven-plugin) on in [samples](https://github.com/dmak/jaxb-xew-plugin/blob/master/samples/jaxb2-maven-plugin/pom.xml). Replacing version to 1.6 worked smoothly for me.

**Comment by valsoray17** [comment]
Ok, I was missing one of the dependencies for xew plugin. It's working now.

Thank you!
