### ISSUE TITLE
-Xjaxbindex plugin from JAXB commons does not work with the xew plugin

### ISSUE THREAD

**Issue by bertramn** [dmak/jaxb-xew-plugin#41]
I recently added `-Xjaxbindex` to the xjc schema compiler and noticed that the generated `jaxb.index` file still contains the public wrapper classes that xew discharges. A quick look in the [jaxb index plugin source](https://java.net/projects/jaxb2-commons/sources/svn/content/basics/tags/0.6.3/basic/src/main/java/org/jvnet/jaxb2_commons/plugin/jaxbindex/JaxbIndexPlugin.java) suggest around line 28 that it is using the overall xjc outline that is passed through the plugins. I did add the `-Xjaxbindex` arg after the `-Xxew` arg in the XJC compiler but it seems xew is not removing the classes it deletes in the generated code from the outline, hence the jaxb index plugin producing a wrong index file.

That's how jaxb index plugin decides what goes into the jaxb.index file:

```java
for (final ClassOutline classOutline : packageOutline.getClasses()) {
...
}
```

Is that hard to fix?

**Comment by dmak** [comment]
Thanks for report.

> xew is not removing the classes it deletes in the generated code from the outline

Well, Xew should do it, at least it attempts to clean up. Perhaps there is still some bug.
You will save my time if you could make a simple maven-based project that demonstrates the problem and share it somehow. You can take any from [examples](https://github.com/dmak/jaxb-xew-plugin/tree/master/samples) as bases. Most logical would be to run `-Xjaxbindex` after `-Xxew`. Let me know what do you expect in `jaxb.index` file.

**Comment by dmak** [comment]
I have analyzed the sources of [`JaxbIndexPlugin`](http://grepcode.com/file/repo1.maven.org/maven2/org.jvnet.jaxb2_commons/jaxb2-basics/0.9.1/org/jvnet/jaxb2_commons/plugin/jaxbindex/JaxbIndexPlugin.java?av=f) and I found the place how Xew can be improved. Please, try the latest [SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/github/jaxb-xew-plugin/jaxb-xew-plugin/1.6-SNAPSHOT/).
