### ISSUE TITLE
Link http://www.conspicio.dk/blog/bjarne/jaxb-xmlelementwrapper-plugin is dead

### ISSUE THREAD

**Issue by michael-o** [dmak/jaxb-xew-plugin#42]
The above link gives 404

**Comment by dmak** [comment]
Duplicate of issue #35.

**Comment by michael-o** [comment]
Why don't you mention that in the README.md?

**Comment by dmak** [comment]
OK, I will. I just wonder why you care :) Internet has many broken links – does it worth efforts to report them all?

**Comment by michael-o** [comment]
Simply annoying having a link in the headline which refers something and turns out to be dead. Why do I care? Currently assessing the JAXB plugins I am using and noticed that this one is used too.

**Comment by dmak** [comment]
Thanks for your message. I have removed the link from the project header.
