### ISSUE TITLE
jaxb2-basic hashCode() and equals() still uses removed classes

### ISSUE THREAD

**Issue by jmattheis** [dmak/jaxb-xew-plugin#43]
The jaxb2-basic which adds hashCode() with -xjc-XhashCode and equals() with -xjc-Xequals still uses classes which were removed by xew, is there support for this or does the xew plugin not support other plugins?
groupId: org.jvnet.jaxb2_commons
artifactId: jaxb2-basics

**Comment by dmak** [comment]
Could you please create a simple tiny project (e.g. can be based on one of [sample](https://github.com/dmak/jaxb-xew-plugin/tree/master/samples) projects) that demonstrates the problem? It would be them much easier for me to investigate it.

**Comment by jmattheis** [comment]
Well, I found out myself, the problem was that in maven at the extraargs i've put the xew arguments under the -xjc-Xequals that produces invalid files, is this somewhere noted? After I put the xew arguments over the other arguments it worked all well.

**Comment by dmak** [comment]
Could you provide the args that worked and that didn't work for you? I have no extrasensory abilities :)

**Comment by jmattheis** [comment]
https://github.com/jmattheis/jaxb-xew-plugin at the cxf example

**Comment by dmak** [comment]
The solution is as simple as to run `-Xequals` and `-XhashCode` *after* `-Xxew`:
```
<extraarg>-xjc-Xxew</extraarg>
<extraarg>-xjc-Xxew:instantiate lazy</extraarg>
<extraarg>-xjc-Xequals</extraarg>
<extraarg>-xjc-XhashCode</extraarg>
```
