### ISSUE TITLE
Information Request: Compatibility with jaxb2-maven-plugin v. 2.x

### ISSUE THREAD

**Issue by fuschl** [dmak/jaxb-xew-plugin#47]
Is it compatible with v. 2.2 of jaxb2-maven-plugin?

[http://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.2/]

**Comment by dmak** [comment]
Could you try it yourself? Take [this example](https://github.com/dmak/jaxb-xew-plugin/tree/master/samples/jaxb2-maven-plugin) and update the plugin version to one you need. Please report _if you find a problem_.

**Comment by dmak** [comment]
Closed as it is not a plugin issue.
