### ISSUE TITLE
Generating Classes for cXML DTD

### ISSUE THREAD

**Issue by jgodara** [dmak/jaxb-xew-plugin#49]
Hello dmak.

I desperately need to generate Java classes by using cXML DTD.

I have tried the command line client but I am running into this error.

```
[ERROR] Property "Name" is already defined. Use &lt;jaxb:property> to resolve this conflict.
  line 489 of file:/C:/STPL%20Stuff/DTD2Java/cXML.dtd

[ERROR] The following location is relevant to the above error
  line 487 of file:/C:/STPL%20Stuff/DTD2Java/cXML.dtd

Failed to parse a schema.
```

I know this is totally doable, but my organization policies does not allow me to spend time on learning the awesome stuff you have made :cry: 

Can you help with my trouble?

The cXML DTD could be found [here](http://xml.cxml.org/schemas/cXML/1.2.014/cXML.dtd).

**Comment by dmak** [comment]
First of all, I don't see the direct relation between xew JAXB plugin and your problem. Could you please clarify it?

If there is no relation, try to search on stackoverflow.com, for example, [How to customize property name in JAXB?](http://stackoverflow.com/questions/27039514/how-to-customize-property-name-in-jaxb)
