### ISSUE TITLE
Doesn't seem to work without jaxb-impl

### ISSUE THREAD

**Issue by eddgrant** [dmak/jaxb-xew-plugin#51]
Hey,

Thanks for creating this plugin, it's _exactly_ what I needed today! Just raising this issue as I followed the Gradle instructions in the readme but got the following error:

    Caused by: com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions
    com.sun.xml.bind.api.impl.NameConverter is an interface, and JAXB can't handle interfaces.
    this problem is related to the following location:
                                                 at com.sun.xml.bind.api.impl.NameConverter
    at public com.sun.xml.bind.api.impl.NameConverter com.sun.tools.xjc.reader.xmlschema.bindinfo.BIGlobalBinding.nameConverter
    at com.sun.tools.xjc.reader.xmlschema.bindinfo.BIGlobalBinding

Managed to resolve this by adding the JAXB impl dependency to my `compile` scope e.g.
    compile 'com.sun.xml.bind:jaxb-impl:2.2.7'

Wasn't sure if this was something just happening to me locally or if it's an omission in the docs.

Thanks again!

Edd

**Comment by dmak** [comment]
Could you please create a simple minimalistic Gradle project that demonstrates the problem? Thanks.

**Comment by eddgrant** [comment]
Sure, attached as [jaxb-xew-plugin-missing-dependency-demonstration.zip](https://github.com/dmak/jaxb-xew-plugin/files/504926/jaxb-xew-plugin-missing-dependency-demonstration.zip)

**Comment by dmak** [comment]
Thanks for demo. Your note is absolutely valid – I will update the documentation. The example helped me to find out the interesting detail: if you remove `<xs:annotation>` from XSD, it compiles just fine:

    <xs:simpleType name="object3" id="object3">
        
        <xs:restriction base="xs:string">
            ...
        </xs:restriction>
    </xs:simpleType>

**Comment by eddgrant** [comment]
Glad it was useful, I guess `xs:annotation` must cause JAXB to utilise some class in the impl dependency that is otherwise unused. Thanks for the quick response.
