### ISSUE TITLE
Plugin not compatible with https://github.com/sabomichal/immutable-xjc

### ISSUE THREAD

**Issue by imavroukakis** [dmak/jaxb-xew-plugin#54]
It seems like the plugin is not compatible with the immutable-xjc plugin. I've tried putting it before and after the immutable command line invocation but unfortunately it doesn't seem to make a difference.

**Comment by dmak** [comment]
Could you package a tiny/minimalistic project that demonstrates the problem, and attach it to the issue?

**Comment by dmak** [comment]
I confirm there is an issue in Xew code which actually needs to update the type of the field. This can only be achieved using reflection (OMG). Another peculiarity is that only instantiationType=lazy will work, as the field is marked final.
Could you please test with [10-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/com/github/jaxb-xew-plugin/jaxb-xew-plugin/1.10-SNAPSHOT/jaxb-xew-plugin-1.10-20180611.172258-2.jar) with `-Xxew:instantiate lazy` XJC argument passed? That should work just fine, see [`samples`](../tree/master/samples/jaxb2-maven-plugin-immutable/pom.xml#L52).
