### ISSUE TITLE
Usage with jaxb2-maven-plugin

### ISSUE THREAD

**Issue by derari** [dmak/jaxb-xew-plugin#60]
The readme suggests to configure the Codehaus jaxb2-maven-plugin with
`<arguments>-no-header -Xxew -Xxew:instantiate lazy</arguments>`
which did not work for me (version 2.4).

Instead I had to do this:
```
<arguments>
    <argument>-Xxew</argument>
    <argument>-Xxew:instantiate lazy</argument>
</arguments>
```

**Comment by dmak** [comment]
I agree that v2.4 of `jaxb2-maven-plugin` requires different syntax, there is an [example](https://github.com/dmak/jaxb-xew-plugin/blob/master/samples/jaxb2-maven-plugin/pom.xml) that covers this. The information in README describes (already relic) case for `jaxb2-maven-plugin` v1.5 which needs some plugin classpath massaging to make it working. IDEs like Eclipse or IDEA resolve plugin configuration options automatically and provide hints / autocompletion, so it is not a big deal.
