### ISSUE TITLE
Using plugin from Eclipse

### ISSUE THREAD

**Issue by l3ender** [dmak/jaxb-xew-plugin#70]
Is it possible to use this plugin from within Eclipse when right clicking on a .wsdl file and using the "Generate Client" option? We have successfully used the plugin from a Maven project, but are finding it quite tedious to do so for every WSDL integration (the project we create to generate proxy objects is a throwaway after we generate the jar file).

I have created a binding file:
```xml
<jaxws:bindings xmlns:jaxws="http://java.sun.com/xml/ns/jaxws">
	<jaxws:enableWrapperStyle>false</jaxws:enableWrapperStyle>
</jaxws:bindings>
```

Then in Eclipse, I right click on the wsdl file to generate proxy objects:

![image](https://user-images.githubusercontent.com/2243641/149235675-eda90ffa-5797-4ba9-9549-c2c02ffbda8a.png)

I enable the option to specify a binding file:

![image](https://user-images.githubusercontent.com/2243641/149235894-85a79a61-cd3f-4371-8f38-fe164b882609.png)

And then select the binding file:

![image](https://user-images.githubusercontent.com/2243641/149236050-c26ba359-6189-49cd-8764-09216078e1d6.png)

But my generated classes still contain the ArrayOfXxx objects.

Is there a way to accomplish it? I am currently using Eclipse 2021-06, j2ee version.

Thank you!

**Comment by dmak** [comment]
It looks like your JAX-WS binding should be inside JAXB binding, see [solution here](https://stackoverflow.com/a/38077750/267197).
