### ISSUE TITLE
ObjectFactory compilation error for collection using complexType

### ISSUE THREAD

**Issue by Rizen59** [dmak/jaxb-xew-plugin#72]
Hi,

The following xsd (valid according to Altova XMLSpy software) produced a compilation error on ObjectFactory at the generation.
It expects the class _**Generation.ProductionStockage.AppointCollection.class**_ to be created but nothing exist in Generation.ProductionStockage.

Without xew plugin the generation works fine. Also if there is only one element in _appoint_collection_.

Plugin used:
- maven-jaxb2-plugin : 0.15.1
- jaxb-xew-plugin : 1.11
- Environment : Java 8 / Maven 3.6.0

```xml

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="generation">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="production_stockage_collection">
          <xs:complexType>
            <xs:sequence minOccurs="0">
              <xs:element name="production_stockage" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:all>
                    <xs:element name="appoint_collection" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                          <xs:element name="joule_effect" type="xs:string" minOccurs="0"/>
                          <xs:element name="combustion" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:all>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

**Comment by dmak** [comment]
Very likely I won't have time to look into that till August...

**Comment by Rizen59** [comment]
Don't worry I can wait until that. Thanks.

It appears 4 methods are created to create elements for _appoint_collection_ :
- createGenerationProductionStockageAppointCollectionJouleEffect
- createGenerationProductionStockageAppointCollectionCombustion
- createGenerationProductionStockageJouleEffect
- createGenerationProductionStockageCombustion

I suppose the problem came from the first two methods that should not be present.
The generated code in Generation.java seems correct to me.

**Comment by Rizen59** [comment]
Hi dmak,
Have you any additional information on that problem?

**Comment by dmak** [comment]
The issue will be fixed in next release. Attaching the playground project ([XEW-72-scoped.zip](https://github.com/dmak/jaxb-xew-plugin/files/10470611/XEW-72-scoped.zip)).
